version: 0.2

env:
    git-credential-helper: yes

phases:
  install:
    runtime-versions:
      php: 7.3
  build:
    commands:
      - composer install --prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs --no-suggest --no-ansi --no-interaction
      - php vendor/composer/satis/bin/satis build satis.json web

cache:
  paths:
    - $COMPOSER_HOME

artifacts:
  base-directory: web
  files:
    - '**/*'
