version: '3.7'

# The nginx can be removed if the web interface is not needed. Remember to also
# add `"output-html": false` to your satis.json configuration file.
services:
    nginx:
        image: nginx
        ports:
            - 8080:80
        volumes:
            - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ../web:/var/www/html:ro

    satis:
        image: composer/satis
        # We do not want to run the build command on start-up, we therefore
        # override it with a no-op command.
        command: 'echo no-op'
        volumes:
            - ../:/build:delegated
            # To authenticate to CodeCommit we need to mount our already configured .ssh
            # directory containing the RSA keys (public and private) and the config file.
            # Follow this guide to create them if needed (step 1-8):
            # https://docs.aws.amazon.com/codecommit/latest/userguide/setting-up-ssh-unixes.html#setting-up-ssh-unixes-keys
            - ~/.ssh:/root/.ssh


